/*
This code reads the density grid file generated by cola_halo.

Density constrast field delta(x) is computed on the fly, if you set
"coarse_grid_nc" in the parameter file. The density field is
calculated by the Clound-In-Cell (CIC) method.

Number of grids per dimension is coarse_grid_nc in the parameter file.

File name:
  grid00001a.b
  00001   -- random seed of realizations
  a,b,c,d -- output_redshifts from high to low
  suffix  -- .b for binary

File format: Binary
  boxsize [4-byte float]
  nc      [4-byte int]
  delta   [4-byte float * nc^3] in C order
  nc      [4-byte int] (for sanity check)

C order means:
  for(int ix=0; ix<nc; ix++)
   for(int iy=0; iy<nc; iy++)
    for(int iz=0; iz<nc; iz++)
      fread(&delta, sizeof(int), 1, fp); // delta(ix,iy,iz)

*/

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

int main()
{
  char filename[]= "grid00001d.b"; 
  float boxsize;
  int nc, nc_check;
  float* delta;
  FILE* fp;
  int ix, iy, iz;

  fp= fopen(filename, "r");

  fread(&boxsize, sizeof(float), 1, fp);
  fread(&nc, sizeof(int), 1, fp);

  delta= malloc(sizeof(float)*nc*nc*nc); 

  fread(delta, sizeof(float), nc*nc*nc, fp);
  fread(&nc_check, sizeof(int), 1, fp);

  if(nc != nc_check) {
    fprintf(stderr, "Error: nc check failed. %d != %d.\n", nc, nc_check);
    return -1;
  }

  fclose(fp);

  //
  // Do anything with the delta
  //   delta(ix, iy, iz) = delta[(ix*nc + iy)*nc + iz]
  //

  printf("# boxsize= %.1f\n", boxsize);
  printf("# nc= %d\n", nc);

  for(ix=0; ix<nc; ix++) {
    for(iy=0; iy<nc; iy++) {
      for(iz=0; iz<nc; iz++) {
	printf("delta(%3d,%3d,%3d) = % e\n", ix, iy, iz, 
	       delta[(ix*nc + iy)*nc + iz]);
      }
    }
  }
  
  free(delta);

  return 0;
}
