/*
This code reads the randomly subsampled particles file generated by cola_halo

Samping ratio is subsample_factor in the parameter file, which gives
the number of particles subsample_factor*nc^3 in average. The actual
number of subsampled particles has statistical fluctuation.

File name:
  sub00001a.b
  00001   -- random seed of realizations
  a,b,c,d -- output_redshift from high to low
  suffix  -- .b for binary

Files format: Binary file
  header: 6*[4-byte float]
    0: Boxsize [1/h Mpc]
    1: Mass of particle m [10^10/h solar mass]
       Total adds up to omega_m*rho_crit*boxsize^3.
    2: Omega_m
    3: Hubble constant h [H0 = 100/h km/s/Mpc]
    4: Scale factor a
    5: Redshift z
  np: [4-byte int]
  positions and velocies: {6*[4-byte float] x,y,z,vx,vy,vz} * np
    x,y,z:    comoving coordinate [1/h Mpc]
    vx,vy,vz: peculiar velocity   [km/s]
  np: [4-byte int] (for sanity check)

File size = 4*(8+6*np) bytes

*/

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

typedef struct {
  float x[3], v[3];
} Particle;

int main()
{
  char filename[]= "sub00001a.b"; 
  
  float header[6];
  int np, np_check;
  Particle* p;
  FILE* fp;
  int i;

  fp= fopen(filename, "r");
  if(fp == 0) {
    fprintf(stderr, "Error: Unable to read particle file: %s\n", filename);
    return -1;
  }

  fread(header, sizeof(float), 6, fp);
  fread(&np, sizeof(int), 1, fp);

  p= malloc(sizeof(Particle)*np); assert(p);

  for(i=0; i<np; i++) {
    fread(p[i].x, sizeof(float), 3, fp);
    fread(p[i].v, sizeof(float), 3, fp);
  }

  // or read all at once if struct `Particle` contains x and v only
  // fread(particles, sizeof(Particle), np, fp);
  
  fread(&np_check, sizeof(int), 1, fp);

  if(np != np_check) {
    fprintf(stderr, "Error: np check failed. %d != %d.\n", np, np_check);
    return -1;
  }

  fclose(fp);

  //
  // Do anything with the particles
  //

  printf("# boxsize= %.1f\n", header[0]);
  printf("# m      = %e\n",   header[1]);
  printf("# omega_m= %.3f\n", header[2]);
  printf("# h      = %.3f\n", header[3]);
  printf("# a      = %.3f\n", header[4]);
  printf("# z      = %.3f\n", header[5]);

  printf("# np (number of particles) = %d\n", np);

  for(i=0; i<np; i++) {
    // Print ascii format similar to fof (with nfof=1)
    printf("1 %e %e %e %e %e %e\n", 
	   p[i].x[0], p[i].x[1], p[i].x[2],
	   p[i].v[0], p[i].v[1], p[i].v[2]);
  }
    
  free(p);

  return 0;
}
